[package]
name = "war3mdlx"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
byteorder = "1"
walkdir = "2"
once_cell = "1.21.3"
glam = "0.30.9"
derive-debug = "0.1.2"
