[package]
name = "war3mdlx"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
byteorder = "1"
walkdir = "2"
once_cell = { version = "1.21.3", registry = "aliyun" }
