# rustfmt.toml
# see: https://rust-lang.github.io/rustfmt/

edition = "2024"
max_width = 120
tab_spaces = 4
use_small_heuristics = "Max"
newline_style = "Unix"
condense_wildcard_suffixes = true
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
match_block_trailing_comma = true
overflow_delimited_expr = true
use_field_init_shorthand = true
use_try_shorthand = true
